import { Designer, Project } from '@/types';

export const DESIGNERS: Designer[] = [
  {
    id: 'hwang-jinsu',
    name: 'Hwang Jinsu',
    nameKo: '황진수',
    role: 'Creative Director',
    bio: 'REDUX의 창립자이자 크리에이티브 디렉터로, 실험적인 패션과 예술의 경계를 탐구합니다.',
    profileImage: '/images/designers/hwang-jinsu/profile.jpg',
    coverImage: '/images/designers/hwang-jinsu/cover.jpg',
    instagramHandle: 'hwangjinsu',
    portfolioImages: [
      '/images/designers/hwang-jinsu/portfolio-1.jpg',
      '/images/designers/hwang-jinsu/portfolio-2.jpg',
      '/images/designers/hwang-jinsu/portfolio-3.jpg',
    ],
    featured: true,
    order: 1,
  },
  {
    id: 'choi-eunsol',
    name: 'Choi Eunsol',
    nameKo: '최은솔',
    role: 'Fashion Designer',
    bio: '전통과 현대를 융합한 독특한 미학을 추구하는 패션 디자이너입니다.',
    profileImage: '/images/designers/choi-eunsol/profile.jpg',
    coverImage: '/images/designers/choi-eunsol/cover.jpg',
    instagramHandle: 'choieunsol',
    portfolioImages: [
      '/images/designers/choi-eunsol/portfolio-1.jpg',
      '/images/designers/choi-eunsol/portfolio-2.jpg',
      '/images/designers/choi-eunsol/portfolio-3.jpg',
    ],
    featured: true,
    order: 2,
  },
  {
    id: 'park-parang',
    name: 'Park Parang',
    nameKo: '박파랑',
    role: 'Visual Artist',
    bio: '시각 예술과 패션의 경계를 넘나드는 멀티미디어 아티스트입니다.',
    profileImage: '/images/designers/park-parang/profile.jpg',
    coverImage: '/images/designers/park-parang/cover.jpg',
    instagramHandle: 'parkparang',
    portfolioImages: [
      '/images/designers/park-parang/portfolio-1.jpg',
      '/images/designers/park-parang/portfolio-2.jpg',
      '/images/designers/park-parang/portfolio-3.jpg',
    ],
    featured: true,
    order: 3,
  },
  {
    id: 'lee-taehyeon',
    name: 'Lee Taehyeon',
    nameKo: '이태현',
    role: 'Fashion Designer',
    bio: '미니멀리즘과 구조적 실루엣을 탐구하는 패션 디자이너입니다.',
    profileImage: '/images/designers/lee-taehyeon/profile.jpg',
    coverImage: '/images/designers/lee-taehyeon/cover.jpg',
    instagramHandle: 'leetaehyeon',
    portfolioImages: [
      '/images/designers/lee-taehyeon/portfolio-1.jpg',
      '/images/designers/lee-taehyeon/portfolio-2.jpg',
      '/images/designers/lee-taehyeon/portfolio-3.jpg',
    ],
    featured: false,
    order: 4,
  },
  {
    id: 'kim-bomin',
    name: 'Kim Bomin',
    nameKo: '김보민',
    role: 'Creative Designer',
    bio: '색채와 텍스처를 통해 감정을 표현하는 크리에이티브 디자이너입니다.',
    profileImage: '/images/designers/kim-bomin/profile.jpg',
    coverImage: '/images/designers/kim-bomin/cover.jpg',
    instagramHandle: 'kimbomin',
    portfolioImages: [
      '/images/designers/kim-bomin/portfolio-1.jpg',
      '/images/designers/kim-bomin/portfolio-2.jpg',
      '/images/designers/kim-bomin/portfolio-3.jpg',
    ],
    featured: false,
    order: 5,
  },
  {
    id: 'kim-gyeongsu',
    name: 'Kim Gyeongsu',
    nameKo: '김경수',
    role: 'Fashion Designer',
    bio: '기능성과 예술성을 결합한 혁신적인 패션을 선보이는 디자이너입니다.',
    profileImage: '/images/designers/kim-gyeongsu/profile.jpg',
    coverImage: '/images/designers/kim-gyeongsu/cover.jpg',
    instagramHandle: 'kimgyeongsu',
    portfolioImages: [
      '/images/designers/kim-gyeongsu/portfolio-1.jpg',
      '/images/designers/kim-gyeongsu/portfolio-2.jpg',
      '/images/designers/kim-gyeongsu/portfolio-3.jpg',
    ],
    featured: false,
    order: 6,
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'redux-2024-collection',
    title: 'REDUX 2024 Collection',
    titleKo: 'REDUX 2024 컬렉션',
    description: 'A revolutionary collection that challenges the boundaries between fashion and art.',
    descriptionKo: '패션과 예술의 경계에 도전하는 혁신적인 컬렉션입니다.',
    category: 'collective',
    designers: ['hwang-jinsu', 'choi-eunsol', 'park-parang'],
    images: [
      '/images/projects/redux-2024/image-1.jpg',
      '/images/projects/redux-2024/image-2.jpg',
      '/images/projects/redux-2024/image-3.jpg',
    ],
    videoUrl: '/videos/redux-2024-collection.mp4',
    date: '2024-03-15',
    featured: true,
    order: 1,
  },
];

export const CATEGORIES = {
  collective: {
    id: 'collective',
    title: 'Collective',
    titleKo: '컬렉티브',
    description: '협업과 공동 창작을 통한 새로운 가능성을 발견합니다',
  },
  'visual-art': {
    id: 'visual-art',
    title: 'Visual Art',
    titleKo: '비주얼 아트',
    description: '시각적 언어로 표현하는 예술적 실험',
  },
  'fashion-film': {
    id: 'fashion-film',
    title: 'Fashion Film',
    titleKo: '패션 필름',
    description: '움직임과 이야기가 있는 패션의 새로운 표현',
  },
  installation: {
    id: 'installation',
    title: 'Installation',
    titleKo: '인스톨레이션',
    description: '공간과 관객이 만나는 통합적 예술 경험',
  },
  memory: {
    id: 'memory',
    title: 'Memory',
    titleKo: '메모리',
    description: '시간과 기억의 흔적을 담은 창작물',
  },
} as const;